session_name: {{ cookiecutter.app_name }}
start_directory: "~/project/{{ cookiecutter.app_name }}"
shell_command_before:
  - workon {{ cookiecutter.app_name }}
windows:
- window_name: Server
  layout: tiled
  panes:
    - shell_command:
        - export FLASK_APP=./autoapp.py
        - export FLASK_DEBUG=1
        - load_nvm
        - npm install
        - npm start
    - ls -lh database.db
- window_name: DB
  panes:
    - shell_command:
        - export FLASK_APP=./autoapp.py
        - export FLASK_DEBUG=1
        - echo flask db init/migrate/upgrade
- window_name: Fabfile
  panes:
    - shell_command:
        - workon env2
        - fab
- window_name: Project
  panes:
    - echo Hello
